services:
  web:
    container_name: server
    build: .
    depends_on:
      - db
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
  db:
    container_name: db
    image: postgres:alpine
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_USER=ketchuser
      - POSTGRES_PASSWORD=secureketchpassword789
      - POSTGRES_DB=takehome
    expose:
      - 5432
    command: postgres